table! {
    /// Representation of the `auth_csrf` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_csrf (csrf_key) {
        /// The `created_at` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `csrf_key` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        csrf_key -> Text,
        /// The `csrf_value` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        csrf_value -> Text,
        /// The `service_id` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Integer,
    }
}

table! {
    /// Representation of the `auth_key` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_key (key_id) {
        /// The `created_at` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `key_id` column of the `auth_key` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        key_id -> Integer,
        /// The `key_name` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_name -> Text,
        /// The `key_value` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_value -> Text,
        /// The `service_id` column of the `auth_key` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Nullable<Integer>,
        /// The `user_id` column of the `auth_key` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Integer>,
    }
}

table! {
    /// Representation of the `auth_service` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_service (service_id) {
        /// The `created_at` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `service_id` column of the `auth_service` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Integer,
        /// The `service_name` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        service_name -> Text,
        /// The `service_url` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        service_url -> Text,
    }
}

table! {
    /// Representation of the `auth_user` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_user (user_id) {
        /// The `created_at` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `user_id` column of the `auth_user` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Integer,
        /// The `user_name` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_name -> Text,
        /// The `user_email` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_email -> Text,
        /// The `user_active` column of the `auth_user` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        user_active -> Bool,
        /// The `user_password_hash` column of the `auth_user` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_password_hash -> Nullable<Text>,
        /// The `user_password_revision` column of the `auth_user` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_password_revision -> Nullable<Integer>,
    }
}

joinable!(auth_csrf -> auth_service (service_id));
joinable!(auth_key -> auth_service (service_id));
joinable!(auth_key -> auth_user (user_id));

allow_tables_to_appear_in_same_query!(auth_csrf, auth_key, auth_service, auth_user,);
