table! {
    /// Representation of the `auth_audit` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_audit (audit_id) {
        /// The `created_at` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `audit_id` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        audit_id -> Text,
        /// The `audit_user_agent` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        audit_user_agent -> Text,
        /// The `audit_remote` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        audit_remote -> Text,
        /// The `audit_forwarded_for` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        audit_forwarded_for -> Nullable<Text>,
        /// The `audit_path` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        audit_path -> Text,
        /// The `audit_data` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        audit_data -> Binary,
        /// The `key_id` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        key_id -> Nullable<Text>,
        /// The `service_id` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Nullable<Text>,
        /// The `user_id` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Text>,
        /// The `user_key_id` column of the `auth_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_key_id -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `auth_csrf` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_csrf (csrf_key) {
        /// The `created_at` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `csrf_key` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        csrf_key -> Text,
        /// The `csrf_value` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        csrf_value -> Text,
        /// The `csrf_ttl` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        csrf_ttl -> Text,
        /// The `service_id` column of the `auth_csrf` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Text,
    }
}

table! {
    /// Representation of the `auth_key` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_key (key_id) {
        /// The `created_at` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `key_id` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_id -> Text,
        /// The `key_is_enabled` column of the `auth_key` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        key_is_enabled -> Bool,
        /// The `key_is_revoked` column of the `auth_key` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        key_is_revoked -> Bool,
        /// The `key_name` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_name -> Text,
        /// The `key_value` column of the `auth_key` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key_value -> Text,
        /// The `service_id` column of the `auth_key` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Nullable<Text>,
        /// The `user_id` column of the `auth_key` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `auth_service` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_service (service_id) {
        /// The `created_at` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `service_id` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        service_id -> Text,
        /// The `service_is_enabled` column of the `auth_service` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        service_is_enabled -> Bool,
        /// The `service_name` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        service_name -> Text,
        /// The `service_url` column of the `auth_service` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        service_url -> Text,
    }
}

table! {
    /// Representation of the `auth_user` table.
    ///
    /// (Automatically generated by Diesel.)
    auth_user (user_id) {
        /// The `created_at` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `user_id` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Text,
        /// The `user_is_enabled` column of the `auth_user` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        user_is_enabled -> Bool,
        /// The `user_name` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_name -> Text,
        /// The `user_email` column of the `auth_user` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_email -> Text,
        /// The `user_password_hash` column of the `auth_user` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_password_hash -> Nullable<Text>,
    }
}

joinable!(auth_audit -> auth_service (service_id));
joinable!(auth_audit -> auth_user (user_id));
joinable!(auth_csrf -> auth_service (service_id));
joinable!(auth_key -> auth_service (service_id));
joinable!(auth_key -> auth_user (user_id));

allow_tables_to_appear_in_same_query!(auth_audit, auth_csrf, auth_key, auth_service, auth_user,);
