/**
 * Single Sign-On API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* User password
*/
export class RequestUserCreatePassword {
    /**
    * User allow password reset flag
    */
    'allowReset': boolean;
    /**
    * User password
    */
    'password': string;
    /**
    * User require password update flag
    */
    'requireUpdate': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowReset",
            "baseName": "allow_reset",
            "type": "boolean"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "requireUpdate",
            "baseName": "require_update",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return RequestUserCreatePassword.attributeTypeMap;
    }
}

