/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestOauth2Token {
    'code'?: string;
    'grantType': string;
    'redirectUri'?: string;
    'refreshToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "grantType",
            "baseName": "grant_type",
            "type": "string"
        },
        {
            "name": "redirectUri",
            "baseName": "redirect_uri",
            "type": "string"
        },
        {
            "name": "refreshToken",
            "baseName": "refresh_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RequestOauth2Token.attributeTypeMap;
    }
}

