/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RequestUserCreatePassword } from './requestUserCreatePassword';

export class RequestUserCreate {
    /**
    * User email address
    */
    'email': string;
    /**
    * User enable flag
    */
    'enable': boolean;
    /**
    * User locale
    */
    'locale': string;
    /**
    * User name
    */
    'name': string;
    'password'?: RequestUserCreatePassword;
    /**
    * User access scope
    */
    'scope': string;
    /**
    * User timezone
    */
    'timezone': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "enable",
            "baseName": "enable",
            "type": "boolean"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "RequestUserCreatePassword"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RequestUserCreate.attributeTypeMap;
    }
}

