/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestUserRead {
    'email'?: Array<string>;
    'id'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "Array<string>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return RequestUserRead.attributeTypeMap;
    }
}

