/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestUserUpdatePassword {
    'allowReset'?: boolean;
    'requireUpdate'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowReset",
            "baseName": "allow_reset",
            "type": "boolean"
        },
        {
            "name": "requireUpdate",
            "baseName": "require_update",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return RequestUserUpdatePassword.attributeTypeMap;
    }
}

