/**
 * Single Sign-On API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResponseClient {
    'enable': boolean;
    'id': string;
    'name': string;
    'redirectUri': string;
    'registerEnable': boolean;
    'registerScope': string;
    'scope': string;
    'uri': string;
    'userScope': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enable",
            "baseName": "enable",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "redirectUri",
            "baseName": "redirect_uri",
            "type": "string"
        },
        {
            "name": "registerEnable",
            "baseName": "register_enable",
            "type": "boolean"
        },
        {
            "name": "registerScope",
            "baseName": "register_scope",
            "type": "string"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "userScope",
            "baseName": "user_scope",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseClient.attributeTypeMap;
    }
}

