/**
 * Single Sign-On API (Public)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResponseUserPassword {
    'allowReset': boolean;
    'createdAt': Date;
    'requireUpdate': boolean;
    '_static': boolean;
    'updatedAt': Date;
    'userId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowReset",
            "baseName": "allow_reset",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "requireUpdate",
            "baseName": "require_update",
            "type": "boolean"
        },
        {
            "name": "_static",
            "baseName": "static",
            "type": "boolean"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseUserPassword.attributeTypeMap;
    }
}

