/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResponseAccessManyData } from './responseAccessManyData';
import { ResponseUserOauth2Provider } from './responseUserOauth2Provider';
import { ResponseUserPassword } from './responseUserPassword';

export class ResponseUser {
    'access'?: ResponseAccessManyData;
    'createdAt': Date;
    'email': string;
    'enable': boolean;
    'id': string;
    'locale': string;
    'name': string;
    'oauth2Provider': Array<ResponseUserOauth2Provider>;
    'oauth2ProviderCount': number;
    'password'?: ResponseUserPassword;
    '_static': boolean;
    'timezone': string;
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "access",
            "baseName": "access",
            "type": "ResponseAccessManyData"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "enable",
            "baseName": "enable",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "oauth2Provider",
            "baseName": "oauth2_provider",
            "type": "Array<ResponseUserOauth2Provider>"
        },
        {
            "name": "oauth2ProviderCount",
            "baseName": "oauth2_provider_count",
            "type": "number"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "ResponseUserPassword"
        },
        {
            "name": "_static",
            "baseName": "static",
            "type": "boolean"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ResponseUser.attributeTypeMap;
    }
}

