FROM sso/build-release:v1 as build

FROM debian:10.3
ENV DEBIAN_FRONTEND="noninteractive"

# gRPC server gRPC port.
EXPOSE 7042

# gRPC server HTTP port.
EXPOSE 7043

# OpenAPI server HTTP port.
EXPOSE 8042

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates libpq-dev \
    && rm -rf /var/lib/apt/lists/*;

# Copy binaries.
COPY --from=build /build/target/release/sso-grpc /usr/local/bin/sso-grpc
COPY --from=build /build/target/release/sso-cli /usr/local/bin/sso-cli
COPY --from=build /build/sso_openapi/sso-openapi /usr/local/bin/sso-openapi
RUN chmod +x /usr/local/bin/sso-grpc \
    /usr/local/bin/sso-cli \
    /usr/local/bin/sso-openapi;

# Default entrypoint.
ENTRYPOINT ["sso-grpc"]
